src/CODEOWNERS
=> feat: set codeowners

src/main/java/it/gov/pagopa/payment/dto/mapper/TransactionInProgress2TransactionResponseMapper.java, src/main/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExt.java, src/main/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImpl.java, src/main/java/it/gov/pagopa/payment/service/MerchantTransactionServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/qrcode/QRCodeAuthPaymentServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/qrcode/QRCodeCancelServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/qrcode/QRCodePreAuthServiceImpl.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImplTest.java, src/test/java/it/gov/pagopa/payment/service/MerchantTransactionServiceTest.java, src/test/java/it/gov/pagopa/payment/service/qrcode/QRCodeAuthPaymentServiceTest.java, src/test/java/it/gov/pagopa/payment/service/qrcode/QRCodeCancelServiceTest.java, src/test/java/it/gov/pagopa/payment/service/qrcode/QRCodePreAuthServiceImplTest.java, src/test/java/it/gov/pagopa/payment/test/fakers/MerchantTransactionDTOFaker.java, src/test/java/it/gov/pagopa/payment/test/fakers/TransactionInProgressFaker.java
* IDP-1098 cannot cancel if expired
=> feat: IDP-1098 cannot cancel if expired (#78)

src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java, src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java, src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java
* fix-429-when-write
* fix-429-when-write
=> feat: fix-429-when-write (#137)

postman/idpay-payment-e2e.postman_collection.json
**Description**
The purpose of this PR is to update the functional tests to add the newly created delete initiative api call.
**List of changes**
-  Updated functional tests: added "Delete initiative" api call after an initiative creation.
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**
=> feat: IDP 1615 adeguamento test payment

pom.xml, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java, src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java, src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java
**List of changes**
-  [IDP-1615](https://pagopa.atlassian.net/browse/IDP-1615) Updated functional tests: added "Delete initiative" api call after an initiative creation.
-  [IDP-1641](https://pagopa.atlassian.net/browse/IDP-1641) Modify performance log and info log
-  [IDP-1641](https://pagopa.atlassian.net/browse/IDP-1641) Modify audit logs
- Updated spring version
[IDP-1618]: https://pagopa.atlassian.net/browse/IDP-1618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IDP-1641]: https://pagopa.atlassian.net/browse/IDP-1641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IDP-1641]: https://pagopa.atlassian.net/browse/IDP-1641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
=> feat: Promote to UAT

src/main/java/it/gov/pagopa/payment/constants/PaymentConstants.java
**Description**
The purpose of this PR is to fix the exception code thrown when trying to authorize a transaction when a user has been suspended on the initiative
**List of changes**
- Modified exception code
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**
=> fix: IDP-1576-Changed user suspended exception code

src/main/java/it/gov/pagopa/payment/constants/PaymentConstants.java
**List of changes**
- [IDP-1576](https://pagopa.atlassian.net/browse/IDP-1576) Modified exception code
[IDP-1576]: https://pagopa.atlassian.net/browse/IDP-1576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IDP-1576]: https://pagopa.atlassian.net/browse/IDP-1576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IDP-1576]: https://pagopa.atlassian.net/browse/IDP-1576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IDP-1576]: https://pagopa.atlassian.net/browse/IDP-1576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Promote to UAT

.devops/deploy-pipelines.yml, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/anchore.yml, .github/workflows/pr-title.yml, .github/workflows/release.yml, Dockerfile
- update anchore action triggers (on push and workflow_dispatch)
- bump to semantic-release v4
- add pull request template
- fix anchor skip steps
- pinning docker build image
- helm to default 5m timeout
=> chore: [IDP-1694] Devops fixes

.github/workflows/anchore.yml
=> chore: release uat

src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeApiRetryable.java, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java, src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java
IDP-1765 allow mongo RequestRateTooLarge exception always retryable for selected API
=> feat: IDP-1765 selected API retryable

pom.xml, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeApiRetryable.java, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java, src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java
=> feat: Release dev

src/main/java/it/gov/pagopa/payment/controller/payment/BRCodePaymentController.java, src/main/java/it/gov/pagopa/payment/controller/payment/BRCodePaymentControllerImpl.java, src/main/java/it/gov/pagopa/payment/dto/brcode/TransactionBRCodeCreationRequest.java, src/main/java/it/gov/pagopa/payment/dto/brcode/TransactionBRCodeResponse.java, src/main/java/it/gov/pagopa/payment/service/payment/BRCodePaymentService.java, src/main/java/it/gov/pagopa/payment/service/payment/BRCodePaymentServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/common/CommonAuthServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/common/CommonCreationServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/qrcode/QRCodeAuthPaymentServiceImpl.java, src/test/java/it/gov/pagopa/payment/service/payment/common/CommonAuthPaymentServiceTest.java
Refactored payment authorization method in a common abstract class
- Refactored payment authroization method in a common abstract class
- Added BRCode controller and service
=> feat: Refactor common auth

src/main/java/it/gov/pagopa/payment/constants/PaymentConstants.java, src/main/java/it/gov/pagopa/payment/controller/payment/CommonPaymentController.java, src/main/java/it/gov/pagopa/payment/controller/payment/CommonPaymentControllerImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/common/CommonCancelServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/common/CommonPreAuthServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/idpaycode/IdpayCodeAuthPaymentServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/qrcode/QRCodeCancelServiceImpl.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/payment/controller/payment/CommonPaymentControllerTest.java, src/test/java/it/gov/pagopa/payment/service/payment/common/CommonPreAuthServiceTest.java, src/test/java/it/gov/pagopa/payment/service/payment/idpaycode/IdpayCodeAuthPaymentServiceImplTest.java
Refactor api for delete transaction
- Change API delete transaction
=> feat: Idp 1971 adeguamento delete trx

src/main/java/it/gov/pagopa/payment/dto/mapper/TransactionInProgress2TransactionResponseMapper.java
Fix a check for qrcode fields
fix check
=> fix: fix create transaction for qrcode field

src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java, src/main/java/it/gov/pagopa/common/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java, src/test/java/it/gov/pagopa/common/mongo/DummySpringRepository.java, src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java, src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java
=> fix: IDP-2003 fix Mongo Retry When Anonymous Repo

Dockerfile, pom.xml, src/main/java/it/gov/pagopa/common/stream/StreamsHealthIndicator.java, src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java, src/test/java/it/gov/pagopa/payment/service/payment/barcode/BarCodeCreationServiceImplTest.java, src/test/java/it/gov/pagopa/payment/service/payment/common/CommonCreationServiceImplTest.java
=> fix: Idp 2016 fix CVE

.github/CODEOWNERS, src/main/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImpl.java, src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestClient.java, src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestSyncClient.java, src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java, src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java, src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryTestIntegrated.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/mongo/singleinstance/AutoConfigureSingleInstanceMongodb.java, src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleEmbeddedMongodbAutoConfiguration.java, src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleInstanceMongodWrapper.java, src/test/java/it/gov/pagopa/payment/BaseIntegrationTest.java, src/test/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImplTest.java, src/test/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImplTestIntegrated.java, src/test/java/it/gov/pagopa/payment/service/payment/expired/QRCodeExpirationServiceImplIntegrationTest.java, src/test/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, src/test/resources/META-INF/spring/org.springframework.boot.test.autoconfigure.data.mongo.AutoConfigureDataMongo.imports, src/test/resources/mongodbEmbeddedDisabled.properties
=> chore: IDP-2102 configuring a single mongodb instance for all tests

src/main/java/it/gov/pagopa/payment/dto/MerchantTransactionDTO.java, src/main/java/it/gov/pagopa/payment/service/MerchantTransactionServiceImpl.java, src/test/java/it/gov/pagopa/payment/service/MerchantTransactionServiceTest.java, src/test/java/it/gov/pagopa/payment/test/fakers/MerchantTransactionDTOFaker.java
- Added channel into MerchantTransactionDTO
- Added check for mapping qrCodePngUrl and qrCodeTextUrl
=> fix: [IDP-2014] added channel in getTransactions

src/main/java/it/gov/pagopa/payment/service/payment/barcode/expired/BarCodeAuthorizationExpiredServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/expired/QRCodeAuthorizationExpiredServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/qrcode/QRCodePreAuthServiceImpl.java
Fix transaction expired properties for authorization in qrCode flow
=> fix: IDP-2104 Fix transaction expired auth minutes for initiatives qrCode

.github/CODEOWNERS, src/main/java/it/gov/pagopa/payment/dto/MerchantTransactionDTO.java, src/main/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImpl.java, src/main/java/it/gov/pagopa/payment/service/MerchantTransactionServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/barcode/expired/BarCodeAuthorizationExpiredServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/expired/QRCodeAuthorizationExpiredServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/qrcode/QRCodePreAuthServiceImpl.java, src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestClient.java, src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestSyncClient.java, src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java, src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java, src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryTestIntegrated.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/mongo/singleinstance/AutoConfigureSingleInstanceMongodb.java, src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleEmbeddedMongodbAutoConfiguration.java, src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleInstanceMongodWrapper.java, src/test/java/it/gov/pagopa/payment/BaseIntegrationTest.java, src/test/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImplTest.java, src/test/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImplTestIntegrated.java, src/test/java/it/gov/pagopa/payment/service/MerchantTransactionServiceTest.java, src/test/java/it/gov/pagopa/payment/service/payment/expired/QRCodeExpirationServiceImplIntegrationTest.java, src/test/java/it/gov/pagopa/payment/test/fakers/MerchantTransactionDTOFaker.java, src/test/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, src/test/resources/META-INF/spring/org.springframework.boot.test.autoconfigure.data.mongo.AutoConfigureDataMongo.imports, src/test/resources/mongodbEmbeddedDisabled.properties
- Added get trx - [PR](https://github.com/pagopa/idpay-payment/pull/203)
- Configuring single mongodb instance for all test - [PR](https://github.com/pagopa/idpay-payment/pull/204)
- Fix transaction expired auth minutes [PR](https://github.com/pagopa/idpay-payment/pull/205)
=> fix: Promote UAT

Dockerfile
=> chore: IDP-2115 fix CVE-2023-44487 on application-insight (#207)

Dockerfile, src/main/java/it/gov/pagopa/common/web/exception/ErrorManager.java, src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java, src/main/java/it/gov/pagopa/common/web/exception/ValidationExceptionHandler.java, src/main/java/it/gov/pagopa/payment/constants/PaymentConstants.java, src/main/java/it/gov/pagopa/payment/dto/AuthPaymentDTO.java, src/main/java/it/gov/pagopa/payment/dto/barcode/TransactionBarCodeResponse.java, src/main/java/it/gov/pagopa/payment/dto/idpaycode/RelateUserResponse.java, src/main/java/it/gov/pagopa/payment/dto/mapper/TransactionInProgress2SyncTrxStatusMapper.java, src/main/java/it/gov/pagopa/payment/dto/mapper/TransactionInProgress2TransactionResponseMapper.java, src/main/java/it/gov/pagopa/payment/dto/qrcode/SyncTrxStatusDTO.java, src/main/java/it/gov/pagopa/payment/dto/qrcode/TransactionResponse.java, src/main/java/it/gov/pagopa/payment/service/payment/barcode/expired/BarCodeAuthorizationExpiredServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/expired/QRCodeAuthorizationExpiredServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/qrcode/QRCodePreAuthServiceImpl.java, src/test/java/it/gov/pagopa/common/web/exception/ErrorManagerTest.java, src/test/java/it/gov/pagopa/payment/controller/payment/BarCodePaymentControllerTest.java, src/test/java/it/gov/pagopa/payment/controller/payment/CommonPaymentControllerTest.java, src/test/java/it/gov/pagopa/payment/controller/payment/IdPayCodePaymentControllerTest.java, src/test/java/it/gov/pagopa/payment/controller/payment/IdPayCodePaymentMilControllerTest.java, src/test/java/it/gov/pagopa/payment/dto/mapper/TransactionInProgress2SyncTrxStatusMapperTest.java, src/test/java/it/gov/pagopa/payment/service/payment/common/CommonStatusTransactionServiceImplTest.java, src/test/java/it/gov/pagopa/payment/test/fakers/SyncTrxStatusFaker.java, src/test/java/it/gov/pagopa/payment/test/fakers/TransactionInProgressFaker.java
=> fix: IDP-2113-adeguamento-payment

src/main/java/it/gov/pagopa/payment/service/MerchantTransactionServiceImpl.java
=> fix: [IDP-2105] handle check channel null

src/main/java/it/gov/pagopa/payment/service/MerchantTransactionServiceImpl.java
Handle mapping with channel null for qrCodePngUrl and qrCodeTxtUrl fields
=> fix: [IDP-2105] handle check channel null (#211)

src/main/java/it/gov/pagopa/payment/controller/payment/CommonPaymentController.java, src/main/java/it/gov/pagopa/payment/controller/payment/CommonPaymentControllerImpl.java, src/main/java/it/gov/pagopa/payment/controller/payment/QRCodePaymentController.java, src/main/java/it/gov/pagopa/payment/controller/payment/QRCodePaymentControllerImpl.java, src/test/java/it/gov/pagopa/payment/controller/payment/BasePaymentControllerIntegrationTest.java, src/test/java/it/gov/pagopa/payment/controller/payment/CommonPaymentControllerTest.java, src/test/java/it/gov/pagopa/payment/controller/payment/QRCodePaymentControllerTest.java
=> fix: moved force expiration API

src/main/java/it/gov/pagopa/common/utils/CommonUtilities.java, src/main/java/it/gov/pagopa/payment/dto/MerchantTransactionDTO.java, src/main/java/it/gov/pagopa/payment/dto/barcode/TransactionBarCodeResponse.java, src/main/java/it/gov/pagopa/payment/dto/mapper/TransactionBarCodeInProgress2TransactionResponseMapper.java, src/main/java/it/gov/pagopa/payment/dto/mapper/TransactionInProgress2TransactionResponseMapper.java, src/main/java/it/gov/pagopa/payment/dto/qrcode/TransactionResponse.java, src/main/java/it/gov/pagopa/payment/service/MerchantTransactionServiceImpl.java, src/test/java/it/gov/pagopa/common/utils/CommonUtilitiesTest.java, src/test/java/it/gov/pagopa/payment/dto/mapper/TransactionInProgress2TransactionResponseMapperTest.java, src/test/java/it/gov/pagopa/payment/test/fakers/MerchantTransactionDTOFaker.java
The purpose of this pr is to change the trx expiration time in the api response when creatin a trx and when retrieving the transactions of a merchant from minutes to seconds
- Modified field from trxExpirationMinutes to trxExpirationSeconds
- Modified JUnit tests
=> fix: IDP-2171 change trx expiration minutes to trx expiration seconds

postman/idpay-payment-e2e.postman_collection.json, src/main/java/it/gov/pagopa/payment/controller/payment/CommonPaymentControllerImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/common/CommonCancelServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/common/CommonConfirmServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/common/CommonCreationServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/common/CommonStatusTransactionServiceImpl.java, src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java, src/test/java/it/gov/pagopa/payment/controller/payment/BasePaymentControllerIntegrationTest.java, src/test/java/it/gov/pagopa/payment/controller/payment/CommonPaymentControllerTest.java, src/test/java/it/gov/pagopa/payment/controller/payment/IdPayCodePaymentControllerIntegrationTest.java, src/test/java/it/gov/pagopa/payment/controller/payment/QRCodePaymentControllerIntegrationTest.java, src/test/java/it/gov/pagopa/payment/service/payment/common/CommonStatusTransactionServiceImplTest.java, src/test/java/it/gov/pagopa/payment/service/payment/expired/QRCodeExpirationServiceImplIntegrationTest.java
=> chore: Idp 1951 refactor payment controller integration test

postman/idpay-payment-e2e.postman_collection.json
=> chore: Using fake cf in e2e test

postman/idpay-payment-e2e.postman_collection.json, src/main/java/it/gov/pagopa/payment/controller/payment/CommonPaymentControllerImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/common/CommonCancelServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/common/CommonConfirmServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/common/CommonCreationServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/common/CommonStatusTransactionServiceImpl.java, src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java, src/test/java/it/gov/pagopa/payment/controller/payment/BasePaymentControllerIntegrationTest.java, src/test/java/it/gov/pagopa/payment/controller/payment/CommonPaymentControllerTest.java, src/test/java/it/gov/pagopa/payment/controller/payment/IdPayCodePaymentControllerIntegrationTest.java, src/test/java/it/gov/pagopa/payment/controller/payment/QRCodePaymentControllerIntegrationTest.java, src/test/java/it/gov/pagopa/payment/service/payment/common/CommonStatusTransactionServiceImplTest.java, src/test/java/it/gov/pagopa/payment/service/payment/expired/QRCodeExpirationServiceImplIntegrationTest.java
* fix: moved force expiration API
* IDP-1951 refactorPaymentControllerIntegrationTest
* IDP-1951 refactorPaymentControllerIntegrationTest
* reducing test timings
* chore: reduced common test timings
* refactor to avoid unnecessary setTimeout
* fixed bean name to adhere to convention
=> chore: Idp 1951 refactor payment controller integration test (#221)

postman/idpay-payment-e2e.postman_collection.json
=> chore: skip e2e tests if 429, then retry

postman/idpay-payment-e2e.postman_collection.json
=> chore: skip e2e tests if 429, then retry (#224)

src/main/java/it/gov/pagopa/common/utils/CommonUtilities.java, src/main/java/it/gov/pagopa/payment/dto/mapper/TransactionInProgress2SyncTrxStatusMapper.java, src/main/java/it/gov/pagopa/payment/dto/mapper/TransactionInProgress2TransactionResponseMapper.java, src/main/java/it/gov/pagopa/payment/dto/qrcode/SyncTrxStatusDTO.java, src/test/java/it/gov/pagopa/payment/dto/mapper/TransactionInProgress2SyncTrxStatusMapperTest.java
- Added splitPayment and residualAmountCents into get status for IDPAYCODE and QRCODE
=> fix: IDP-2206 IDP-2204 Added splitPayment and residualAmountCents fields

postman/idpay-payment-e2e.postman_collection.json
=> chore: IDP-2192 adequating Test E2E To Ko If Admissibility NotReady

Dockerfile, pom.xml, src/main/java/it/gov/pagopa/payment/service/payment/barcode/BarCodeAuthPaymentServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/common/CommonAuthServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/common/CommonPreAuthServiceImpl.java, src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java, src/test/java/it/gov/pagopa/payment/BaseIntegrationTest.java, src/test/java/it/gov/pagopa/payment/controller/payment/BasePaymentControllerIntegrationTest.java, src/test/java/it/gov/pagopa/payment/service/payment/idpaycode/IdpayCodePreAuthServiceTest.java
=> fix: IDP-2196 fix Cve

helm/values.yaml
- Update transaction topic configuration
=> chore: [Idp 2286] aggiornamento configurazione coda idpay transaction

src/main/java/it/gov/pagopa/payment/connector/rest/reward/RewardCalculatorConnectorImpl.java, src/main/java/it/gov/pagopa/payment/connector/rest/reward/RewardCalculatorRestClient.java, src/main/java/it/gov/pagopa/payment/connector/rest/reward/dto/AuthPaymentResponseDTO.java, src/main/java/it/gov/pagopa/payment/connector/rest/reward/mapper/RewardCalculatorMapper.java, src/main/java/it/gov/pagopa/payment/dto/AuthPaymentDTO.java, src/main/java/it/gov/pagopa/payment/model/TransactionInProgress.java, src/main/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExt.java, src/main/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/common/CommonPreAuthServiceImpl.java, src/test/java/it/gov/pagopa/payment/connector/rest/reward/RewardCalculatorRestClientTest.java, src/test/java/it/gov/pagopa/payment/connector/rest/reward/mapper/RewardCalculatorMapperTest.java, src/test/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImplTest.java, src/test/java/it/gov/pagopa/payment/service/payment/common/CommonPreAuthServiceTest.java, src/test/java/it/gov/pagopa/payment/service/payment/idpaycode/IdpayCodePreAuthServiceTest.java, src/test/java/it/gov/pagopa/payment/service/payment/qrcode/QRCodePreAuthServiceImplTest.java, src/test/java/it/gov/pagopa/payment/test/fakers/AuthPaymentDTOFaker.java, src/test/java/it/gov/pagopa/payment/test/fakers/TransactionInProgressFaker.java, src/test/resources/mappings/reward/authorize_OK.json, src/test/resources/mappings/reward/cancel_OK.json, src/test/resources/mappings/reward/preview_FORBIDDEN.json, src/test/resources/mappings/reward/preview_GENERIC_ERROR.json, src/test/resources/mappings/reward/preview_TOO_MANY_REQUEST.json, src/test/resources/mappings/reward/preview_WITHOUT_ETAG.json, src/test/resources/mappings/reward/preview_WITH_BAD_ETAG.json, src/test/resources/mappings/reward/preview_WITH_ETAG.json
[IDP-2280](https://pagopa.atlassian.net/browse/IDP-2280)
- Changed previewTransaction of RewardCalculatorConnector in order to get etag from header
- Added counterVersion in model TransactionInProgress 
- Changed Junit 
- To handle new transactionality
[IDP-2280]: https://pagopa.atlassian.net/browse/IDP-2280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: [IDP-2280] Aligned reward calculator connector preview with etag

src/main/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExt.java, src/main/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/common/CommonCancelServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/common/CommonConfirmServiceImpl.java, src/test/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImplTest.java, src/test/java/it/gov/pagopa/payment/service/payment/common/CommonCancelServiceTest.java, src/test/java/it/gov/pagopa/payment/service/payment/common/CommonConfirmServiceImplTest.java
=> feat: IDP-2462 Removed method findByIdThrottled

specs/asyncapi.yml
- Added asyncapi.yml file with async queue census
=> chore: Idp 2339 async queue census

src/main/java/it/gov/pagopa/payment/configuration/ServiceExceptionConfig.java, src/main/java/it/gov/pagopa/payment/connector/rest/reward/RewardCalculatorConnectorImpl.java, src/main/java/it/gov/pagopa/payment/constants/PaymentConstants.java, src/main/java/it/gov/pagopa/payment/exception/custom/TransactionAlreadyCancelledException.java, src/test/java/it/gov/pagopa/payment/connector/rest/reward/RewardCalculatorRestClientTest.java, src/test/resources/stub/mappings/reward/authALREADY_AUTHORIZED.json, src/test/resources/stub/mappings/reward/cancel_ALREADY_CANCELLED.json
[IDP-2519](https://pagopa.atlassian.net/browse/IDP-2519)
[IDP-2519]: https://pagopa.atlassian.net/browse/IDP-2519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [IDP-2519] Exception adjustment

specs/asyncapi.yml
- Update DeleteInitiative reference on async file
=> chore: update async reference

.grype.yaml, Dockerfile, pom.xml
- Update amazoncorretto and  tomcat-embed-core version
=> fix: [IDP-2561] fix cve docker and tomcat

.grype.yaml, Dockerfile, pom.xml, src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java
- Update spring dependencies
- Update grype ignore
=> chore: fix cve

pom.xml
=> chore: promote to UAT

helm/values-prod.yaml, helm/values-uat.yaml
=> chore: helm fix

.github/workflows/anchore.yml, Dockerfile, pom.xml
[IDP-2676]: https://pagopa.atlassian.net/browse/IDP-2676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: [IDP-2676] jdk update to 21

src/main/java/it/gov/pagopa/payment/controller/PointOfSaleTransactionController.java, src/main/java/it/gov/pagopa/payment/controller/PointOfSaleTransactionControllerImpl.java, src/main/java/it/gov/pagopa/payment/dto/PointOfSaleTransactionDTO.java, src/main/java/it/gov/pagopa/payment/dto/PointOfSaleTransactionsListDTO.java, src/main/java/it/gov/pagopa/payment/dto/mapper/PointOfSaleTransactionMapper.java, src/main/java/it/gov/pagopa/payment/model/TransactionInProgress.java, src/main/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExt.java, src/main/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImpl.java, src/main/java/it/gov/pagopa/payment/service/PDVService.java, src/main/java/it/gov/pagopa/payment/service/PDVServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/PointOfSaleTransactionService.java, src/main/java/it/gov/pagopa/payment/service/PointOfSaleTransactionServiceImpl.java, src/test/java/it/gov/pagopa/payment/controller/PointOfSaleTransactionControllerTest.java, src/test/java/it/gov/pagopa/payment/dto/mapper/PointOfSaleTransactionMapperTest.java, src/test/java/it/gov/pagopa/payment/dto/mapper/barcode/TransactionBarCodeCreationRequest2TransactionInProgressMapperTest.java, src/test/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImplTest.java, src/test/java/it/gov/pagopa/payment/service/PDVServiceImplTest.java, src/test/java/it/gov/pagopa/payment/service/PointOfSaleTransactionServiceTest.java, src/test/java/it/gov/pagopa/payment/test/fakers/PointOfSaleTransactionDTOFaker.java, src/test/java/it/gov/pagopa/payment/test/fakers/TransactionInProgressFaker.java
Added new endpoint to fetch all in-progress transactions associated to a point of sale.
Introduction of the pointOfSaleId field in the model TransactionInProgress.
Implemented new API to retrieve in-progress transactions associated to a point of sale.
Implemented unit tests related to the new feature.
This change is required to allow retrieval of a point of sale's transaction history when accessing its detail page.
=> feat: [EBE-69] New API to retrieve in-progress transactions

src/main/java/it/gov/pagopa/payment/dto/PointOfSaleTransactionDTO.java
=> fix: EBE-69 rename trxId to id in JSON response for FE compatibility

src/main/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImpl.java
Prevent empty status from affecting transaction query results.
=> fix: EBE-69 ignore empty status filter in transaction query

src/main/java/it/gov/pagopa/payment/controller/PointOfSaleTransactionControllerImpl.java
=> fix: Fixed issue on PointOfSalesTransactionControllerImpl logs

src/main/java/it/gov/pagopa/payment/dto/barcode/AuthBarCodePaymentDTO.java, src/test/java/it/gov/pagopa/payment/controller/payment/BarCodePaymentControllerTest.java
=> chore: Fix authbarcodepaymentdto

src/main/java/it/gov/pagopa/payment/controller/payment/BarCodePaymentController.java, src/main/java/it/gov/pagopa/payment/controller/payment/BarCodePaymentControllerImpl.java, src/main/java/it/gov/pagopa/payment/repository/TransactionInProgressRepository.java, src/main/java/it/gov/pagopa/payment/service/payment/BarCodePaymentService.java, src/main/java/it/gov/pagopa/payment/service/payment/BarCodePaymentServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/barcode/RetrieveActiveBarcode.java, src/main/java/it/gov/pagopa/payment/service/payment/barcode/RetrieveActiveBarcodeImpl.java, src/test/java/it/gov/pagopa/payment/controller/payment/BarCodePaymentControllerTest.java, src/test/java/it/gov/pagopa/payment/service/payment/BarCodePaymentServiceImplTest.java, src/test/java/it/gov/pagopa/payment/service/payment/barcode/RetrieveActiveBarcodeTest.java
- Added Api for retrieve voucher
=> feat: [UPBE-192] Added GET payment API

src/main/java/it/gov/pagopa/payment/controller/payment/BarCodePaymentController.java, src/main/java/it/gov/pagopa/payment/controller/payment/BarCodePaymentControllerImpl.java, src/main/java/it/gov/pagopa/payment/controller/payment/CommonPaymentController.java, src/main/java/it/gov/pagopa/payment/controller/payment/CommonPaymentControllerImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/BarCodePaymentService.java, src/main/java/it/gov/pagopa/payment/service/payment/BarCodePaymentServiceImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/barcode/BarCodeCaptureService.java, src/main/java/it/gov/pagopa/payment/service/payment/barcode/BarCodeCaptureServiceImpl.java, src/test/java/it/gov/pagopa/payment/controller/payment/BarCodePaymentControllerTest.java, src/test/java/it/gov/pagopa/payment/controller/payment/CommonPaymentControllerTest.java, src/test/java/it/gov/pagopa/payment/service/payment/BarCodeCaptureServiceImplTest.java, src/test/java/it/gov/pagopa/payment/service/payment/BarCodePaymentServiceImplTest.java, src/test/java/it/gov/pagopa/payment/service/payment/barcode/BarCodeCaptureServiceImplTest.java
=> fix: EBE-187 move api under barcode

src/main/java/it/gov/pagopa/payment/service/payment/barcode/BarCodeCreationServiceImpl.java, src/test/java/it/gov/pagopa/payment/service/payment/barcode/BarCodeCreationServiceImplTest.java
- disable check wallet into create extended transaction internal flow
=> fix: [UPBE-191] disable check wallet into create extended transaction internal flow

src/main/java/it/gov/pagopa/payment/controller/payment/CommonPaymentController.java, src/main/java/it/gov/pagopa/payment/controller/payment/CommonPaymentControllerImpl.java, src/main/java/it/gov/pagopa/payment/dto/CancelTransactionAuditDTO.java, src/main/java/it/gov/pagopa/payment/service/payment/common/CommonCancelServiceImpl.java, src/main/java/it/gov/pagopa/payment/utils/AuditUtilities.java, src/test/java/it/gov/pagopa/payment/controller/payment/CommonPaymentControllerTest.java, src/test/java/it/gov/pagopa/payment/service/payment/common/CommonCancelServiceTest.java, src/test/java/it/gov/pagopa/payment/utils/AuditUtilitiesTest.java
Added support for cancelling a transaction in progress via the DELETE /idpay/payment/{transactionId} API, propagating the point-of-sale ID as required.
=> feat: [Ebe 148] add request header on CommonPaymentController, Add new DTO and fix test

src/main/java/it/gov/pagopa/payment/dto/barcode/TransactionBarCodeCreationRequest.java, src/main/java/it/gov/pagopa/payment/dto/barcode/TransactionBarCodeResponse.java, src/main/java/it/gov/pagopa/payment/dto/mapper/TransactionBarCodeCreationRequest2TransactionInProgressMapper.java, src/main/java/it/gov/pagopa/payment/dto/mapper/TransactionBarCodeInProgress2TransactionResponseMapper.java, src/main/java/it/gov/pagopa/payment/model/TransactionInProgress.java, src/main/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/barcode/BarCodeCreationServiceImpl.java, src/test/java/it/gov/pagopa/payment/dto/mapper/barcode/TransactionBarCodeCreationRequest2TransactionInProgressMapperTest.java, src/test/java/it/gov/pagopa/payment/dto/mapper/barcode/TransactionBarCodeInProgress2TransactionResponseMapperTest.java, src/test/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImplTest.java, src/test/java/it/gov/pagopa/payment/service/payment/barcode/BarCodeCreationServiceImplTest.java, src/test/java/it/gov/pagopa/payment/service/payment/common/CommonPreAuthServiceTest.java
management of the new voucherAmountCents field
=> feat: [UPBE-226] management of the new voucherAmountCents field

src/main/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImpl.java
Changed product category sorting field.
Updated product category sorting field from:
- Cappa -> Cappa da cucina
- Frigorifero -> Apparecchio di refrigerazione
=> fix: updated product category sorting field

src/main/java/it/gov/pagopa/payment/controller/payment/BarCodePaymentController.java, src/main/java/it/gov/pagopa/payment/controller/payment/BarCodePaymentControllerImpl.java, src/main/java/it/gov/pagopa/payment/service/pdf/PdfService.java, src/main/java/it/gov/pagopa/payment/service/pdf/PdfServiceImpl.java, src/test/java/it/gov/pagopa/payment/controller/payment/BarCodePaymentControllerTest.java, src/test/java/it/gov/pagopa/payment/service/pdf/PdfServiceImplTest.java
modified junit
changed barcode return to base64
modified junit
=> feat: UPBE-220 changed barcode return to base64

src/main/java/it/gov/pagopa/payment/service/pdf/PdfServiceImpl.java
fix double divide trxBarcode.getVoucherAmountCents()
=> fix: Upbe 220 fix double divide amount

src/main/java/it/gov/pagopa/payment/controller/payment/BarCodePaymentControllerImpl.java
- performance body cast in retrieve transaction flow
=> fix: performance body cast in retrieve transaction flow

src/main/java/it/gov/pagopa/payment/controller/payment/BarCodePaymentControllerImpl.java, src/main/java/it/gov/pagopa/payment/controller/payment/CommonPaymentControllerImpl.java
=> fix: fixing performance logger (#384)

src/main/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImpl.java, src/main/java/it/gov/pagopa/payment/utils/AggregationConstants.java, src/test/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImplTest.java
Updated product sorting.
Changed product sorting, now it uses additionalProperties.productName.
Updated unit tests.
=> fix: [EBE-224] update product sorting

src/main/java/it/gov/pagopa/payment/dto/PreviewPaymentDTO.java, src/main/java/it/gov/pagopa/payment/service/payment/barcode/BarCodeAuthPaymentServiceImpl.java
Aggiunto e popolato il campo extendedAuthorization in risposta all'API di Preview
Aggiunto il campo nel DTO e mappato sulla risposta dell'API di preview.
=> feat: [EBE-240] - Aggiungere e popolare il campo extendedAuthorization in risposta all'API di Preview

src/main/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExt.java, src/main/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImpl.java, src/main/java/it/gov/pagopa/payment/service/payment/expired/common/CommonAuthorizationExpiredServiceImpl.java, src/test/java/it/gov/pagopa/payment/repository/TransactionInProgressRepositoryExtImplTest.java, src/test/java/it/gov/pagopa/payment/service/payment/expired/barcode/BarCodeAuthorizationExpiredServiceImplTest.java, src/test/java/it/gov/pagopa/payment/service/payment/expired/qrcode/QRCodeAuthorizationExpiredServiceImplTest.java
Change long voucher expiration validation from 5 minutes to 10 days
Ensure short barcode expires after 5 minutes and long barcode after 10 days
=> feat: [EBE-212] Promote to UAT Change validation expire from 5 minute to 10 days 

src/main/java/it/gov/pagopa/payment/service/payment/common/CommonCancelServiceImpl.java, src/test/java/it/gov/pagopa/payment/service/payment/common/CommonCancelServiceTest.java
=> feat: Ebe 231 rework

src/main/java/it/gov/pagopa/payment/configuration/FileStorageConfig.java, src/main/resources/application.yml
=> feat: Refactoring Azure Blob Storage Client
